// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// metaphone
CharacterVector metaphone(CharacterVector word, int maxCodeLen);
RcppExport SEXP phonics_metaphone(SEXP wordSEXP, SEXP maxCodeLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type word(wordSEXP);
    Rcpp::traits::input_parameter< int >::type maxCodeLen(maxCodeLenSEXP);
    __result = Rcpp::wrap(metaphone(word, maxCodeLen));
    return __result;
END_RCPP
}
// soundex
CharacterVector soundex(CharacterVector word, int maxCodeLen);
RcppExport SEXP phonics_soundex(SEXP wordSEXP, SEXP maxCodeLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type word(wordSEXP);
    Rcpp::traits::input_parameter< int >::type maxCodeLen(maxCodeLenSEXP);
    __result = Rcpp::wrap(soundex(word, maxCodeLen));
    return __result;
END_RCPP
}
// refinedSoundex
CharacterVector refinedSoundex(CharacterVector word, int maxCodeLen);
RcppExport SEXP phonics_refinedSoundex(SEXP wordSEXP, SEXP maxCodeLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type word(wordSEXP);
    Rcpp::traits::input_parameter< int >::type maxCodeLen(maxCodeLenSEXP);
    __result = Rcpp::wrap(refinedSoundex(word, maxCodeLen));
    return __result;
END_RCPP
}
