# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

metaphone_internal <- function(word, maxCodeLen = 10L) {
    .Call('_phonics_metaphone_internal', PACKAGE = 'phonics', word, maxCodeLen)
}

#' @useDynLib phonics
#' @importFrom Rcpp evalCpp
soundex_internal <- function(word, maxCodeLen = 4L) {
    .Call('_phonics_soundex_internal', PACKAGE = 'phonics', word, maxCodeLen)
}

#' @useDynLib phonics
#' @importFrom Rcpp evalCpp
refinedSoundex_internal <- function(word, maxCodeLen = 10L) {
    .Call('_phonics_refinedSoundex_internal', PACKAGE = 'phonics', word, maxCodeLen)
}

