# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname metaphone
#' @name metaphone
#' @title metaphone
#'
#' @description Encode a string with the Metaphone phonentic algorithm
#'
#' @param word        character vector of strings to encode
#' @param maxCodeLen  maximum length of the resulting encodings, in characters
#'
#' @details The function \code{metaphone} phonentically encodes the '
#' given string using the metaphone algorithm.  There is some discrepency
#' with respect to how the metaphone algorithm actually works.  For '
#' instance, there is a version in the Java Apache Commons library.  '
#' There is a version provided within PHP.  These do not provide the same
#' results.  On the questionable theory that the implementation in PHP
#' is probably more well known, this code should match it in output.
#'
#' This implementation is based on a Javascript implementation which is
#' itself based on the PHP internal implementation.
#'
#' The variable \code{maxCodeLen} is the limit on how long the returned
#' metaphone should be.
#'
#' @return metaphone encoded character vector
#'
#' @family phonics
#'
#' @examples
#' metaphone("wheel")
#' metaphone(c("school", "benji"))
#'
#' @useDynLib phonics
#' @importFrom Rcpp evalCpp
#' @export
metaphone <- function(word, maxCodeLen = 10L) {
    .Call('phonics_metaphone', PACKAGE = 'phonics', word, maxCodeLen)
}

